## This configuration was generated by terraform-provider-oci

resource "oci_license_manager_configuration" "license" {
  compartment_id = "ocid1.tenancy.oc1..aaaaaaaagxra3x2chdjhoebgoulqchndl53vmavq5znr3vkp6m4a2fcoebsa"
  email_ids = [
  ]
}

