## This configuration was generated by terraform-provider-oci

resource "oci_core_nat_gateway" "arthur_nat" {
  block_traffic  = "false"
  compartment_id = oci_license_manager_configuration.license.id
  display_name   = "arthur_nat_gw"
  public_ip_id   = "ocid1.publicip.oc1.ap-melbourne-1.aaaaaaaab4jixpoysxnjqwiu7e7gbfo2hz6v43wj46y6byjdu3rrmm43jwxq"
  vcn_id         = oci_core_vcn.arthur_vcn.id
}

resource "oci_core_vcn" "arthur_vcn" {
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = oci_license_manager_configuration.license.id

  display_name = "arthur_vcn"
  dns_label    = "arthur"
}

resource "oci_core_internet_gateway" "arthur_igw" {
  compartment_id = oci_license_manager_configuration.license.id
  display_name   = "arthur_igw"
  enabled        = "true"
  vcn_id         = oci_core_vcn.arthur_vcn.id
}

resource "oci_core_default_dhcp_options" "arthur_vcn_default_dhcp" {
  compartment_id   = oci_license_manager_configuration.license.id
  display_name     = "arthur_vcn_default_dhcp"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.arthur_vcn.default_dhcp_options_id
  options {
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    search_domain_names = [
      "arthur.oraclevcn.com",
    ]
    type = "SearchDomain"
  }
}

resource "oci_core_route_table" "arthur_private_route" {
  compartment_id = oci_license_manager_configuration.license.id
  display_name   = "arthur_private_route"
  route_rules {
    description       = "traffic to the internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.arthur_nat.id
  }
  route_rules {
    description       = "traffic to OCI services"
    destination       = "all-mel-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.arthur_sgw.id
  }
  vcn_id = oci_core_vcn.arthur_vcn.id
}

resource "oci_core_default_route_table" "arthur_public_route" {
  compartment_id             = oci_license_manager_configuration.license.id
  display_name               = "arthur_public_route"
  manage_default_resource_id = oci_core_vcn.arthur_vcn.default_route_table_id
  route_rules {
    description       = "traffic to/from internet"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.arthur_igw.id
  }
}

resource "oci_core_service_gateway" "arthur_sgw" {
  compartment_id = oci_license_manager_configuration.license.id
  display_name   = "arthur_sgw"
  services {
    service_id = "ocid1.service.oc1.ap-melbourne-1.aaaaaaaa6ps2w6fdmzftuo5rplyuxi43auws5zd5rhzhygutw5kkql6r3vnq"
  }
  vcn_id = oci_core_vcn.arthur_vcn.id
}

