commonLabels:
  release: production
  author: jacksonrakena
namespace: production

resources:
  # Nginx
  - nginx/

  # Certificates
  - secrets/rakena-cert.yaml
  - secrets/streamapps-cert.yaml
  - ingress-issuer.yaml

  # Secrets
  - secrets/gh-container-registry.yaml
  - secrets/galahad-secret.yaml
  - secrets/gradekeeper-config.yaml
  - secrets/jacksonbot-config.yaml
  - secrets/streamapps-config.yaml
  - secrets/streamapps-config-shim.yaml
  - secrets/identity-config.yaml
  - secrets/identity-env.yaml
  - secrets/mc-config.yaml

  # App stack
  - ../stack

  # Ingresses
  - gitea-ingress-config.yaml
  - ingress.yml
