apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
spec:
  storageClassName: "oci-free"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          envFrom:
            - configMapRef:
                name: mc-config
          ports:
            - containerPort: 25565
            - containerPort: 8080
          volumeMounts:
            - name: gitea-data
              mountPath: /data
              subPath: minecraft
            - name: gitea-data
              mountPath: /downloads
              subPath: minecraft-downloads
        - name: gitea
          image: gitea/gitea:1.21.2
          ports:
            - containerPort: 3000
            - containerPort: 22
          volumeMounts:
            - name: gitea-data
              mountPath: /data
              subPath: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - port: 25565
      protocol: TCP
      targetPort: 25565
      name: minecraft
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: minecraft-map-tcp
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: http-tcp
    - port: 22
      protocol: TCP
      targetPort: 22
      name: ssh-tcp
  selector:
    app: gitea
  type: ClusterIP
