apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradekeeper-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: gradekeeper-server
  template:
    metadata:
      labels:
        app: gradekeeper-server
    spec:
      containers:
        - name: server
          image: ghcr.io/jacksonrakena/gradekeeper-server:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gradekeeper-config
      imagePullSecrets:
        - name: gh-container-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gradekeeper-server
  name: gradekeeper-server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: gradekeeper-server
  type: ClusterIP
