apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacksonbot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jacksonbot
  template:
    metadata:
      labels:
        app: jacksonbot
    spec:
      volumes:
        - name: jacksonbot-config-mount
          configMap:
            name: jacksonbot-config
      containers:
        - name: bot
          image: ghcr.io/jacksonrakena/jacksonbot:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: jacksonbot-config-mount
              mountPath: /app/jacksonbot.appsettings.json
              subPath: jacksonbot.appsettings.json
      imagePullSecrets:
        - name: gh-container-registry
