apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxbudget
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mxbudget
  template:
    metadata:
      labels:
        app: mxbudget
    spec:
      containers:
        - name: mxbudget
          image: ghcr.io/jacksonrakena/mx:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mxbudget-config
      imagePullSecrets:
        - name: gh-container-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mxbudget
  name: mxbudget
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: mxbudget
  type: ClusterIP
