apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  loadBalancerIP: 158.179.25.151
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: websecure
      port: 443
      targetPort: websecure
  selector:
    app: traefik
