kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.4
          args:
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls=true
            - --log.level=trace
            - --providers.kubernetesingress=true
          ports:
            - name: websecure
              containerPort: 443
