apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamapps-shim
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: streamapps-shim
  template:
    metadata:
      labels:
        app: streamapps-shim
    spec:
      volumes:
        - name: streamapps-config-mount
          configMap:
            name: streamapps-config-shim
      containers:
        - name: server
          image: ghcr.io/jacksonrakena/streamapps-server@sha256:4b4674cb11f56c7989d1b8b087989f66e868098a9241f4e16659fdc414a42569
          ports:
            - containerPort: 80
          volumeMounts:
            - name: streamapps-config-mount
              mountPath: /app/secrets.json
              subPath: secrets.json
      imagePullSecrets:
        - name: gh-container-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamapps-shim
  name: streamapps-shim
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: streamapps-shim
  type: ClusterIP
