apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jackson@rakena.co.nz
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: default-class
