commonLabels:
  release: production
  author: jacksonrakena
namespace: production

secretGenerator:
  - name: galahad-pg
    envs:
      - secrets/galahad-secret.env
  - name: rakena-com-au-cert
    type: "kubernetes.io/tls"
    files:
      - secrets/cert-rakena.com.au/tls.crt
      - secrets/cert-rakena.com.au/tls.key
  - name: rakena-cert
    type: "kubernetes.io/tls"
    files:
      - secrets/cert-rakena.co.nz/tls.crt
      - secrets/cert-rakena.co.nz/tls.key
  - name: gh-container-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/docker-registry-config.json

configMapGenerator:
  - name: mc-config
    envs:
      - secrets/mc-config.env
  - name: jacksonbot-config
    files:
      - jacksonbot.appsettings.json=secrets/jacksonbot-config.json
  - name: gradekeeper-config
    envs:
      - secrets/gradekeeper-server.env
  - name: mxbudget-config
    envs:
      - secrets/mxbudget.env
  - name: keycloak-config
    envs:
      - secrets/keycloak.env

resources:
  # Nginx
  - nginx/

  # Let's Encrypt configuration
  - ingress-issuer.yaml

  # App stack
  - ../../stack

  # Ingresses
  - gitea-ingress-config.yaml
  - ingress.yml
